### ISSUE TITLE
Game Parameters are not documented in Wiki

### ISSUE THREAD

**Issue by stheid** [marcusgia2505/classEx_doc#1]
Game parameters are not mentioned at all https://classex.uni-passau.de/wiki/index.php?title=Game

Additionally it is important to know what happens if they are overwritten or if they can be overwritten.

e.g. If i create a parameter $kontostand. What would happen if i write this variable in the subject program code? 
1. Is it overwritten for all players?
1. is the parameter handled as a initial value?
1. Does the program crash?

**Comment by gamer01** [comment]
Actually neigther is true. The programs don't crash, but the values are _read-only_
